version: '3.8'
services:
  server:
    # image: 'nginx'
    build:
      context: . #o contexto muda por conta dos comandos de COPY dentro do nginx.dockerfile 
      dockerfile: ./dockerfiles/nginx.dockerfile
    volumes:
      - './src:/var/www/html'
      - './nginx:/etc/nginx/conf.d'
    ports:
      - '8000:80'
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mariadb
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
  npm:
    image: node:16-alpine
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
      - ./src:/var/www/html